modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="vendshops"
version="${file.jarVersion}"
displayName="VendShops"
logoFile="logo.png"
authors="z1haze"
description='''
Vending Machine Player Shops
'''
[[dependencies.vendshops]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.vendshops]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
